### ISSUE TITLE
Screen tearing since upgrade to Ubuntu 14.10

### ISSUE THREAD

**Issue by dehuszar** [pfps/yoga-laptop#28]
I have had the orientation and sensors working pretty well in Ubuntu 14.04, but upon the upgrade to 14.10, I've been experiencing screen tearing when flipping into tent mode directly from the default orientation.

If I rotate to the vertical orientation first and then go upside-down, then it seems to transition smoothly, but from default to upside-down orientation causes the viewport to show inverted duplications of the bottom half of the screen and duplicate cursors for each orientation.

I've tried both with just the compiled orientation program and also with the compiled ideapad-laptop module, just to make sure I wasn't seeing the issue because the orientation program was expecting something to be in place.  The sensors program won't compile (and the docs advise against using it), but the default 3.16 sensors drivers seem to be otherwise working okay.

I've attached a screenshot so you can see what I mean.

![screen tearing example](https://cloud.githubusercontent.com/assets/617658/4969671/7c374614-6867-11e4-90e9-22c2ff18a2ce.png)

Thanks in advance,
Sam

**Comment by tobbyd** [comment]
It seems to be a problem with the intel graphics driver.  
Compiling latest intel driver (xf86-video-intel - 2.99.917) fixed it for me (Yoga 3 Pro): 
https://01.org/linuxgraphics/downloads 

It also fixed the broken shadows of windows in Gnome 3.

**Comment by jymbob** [comment]
I can also confirm no tearing with latest intel drivers on Ubuntu 14.10

PPA with latest drivers: https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers
