### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by interneteur** [pfps/yoga-laptop#40]
So I went through the readme and installed all the missing depencies.  I have kernel 3.16.0-38.
I'm not sure if I am doing it correctly though, I pulled the git.  Extracted the tar. 

Not sure if it ran already or not, but when I run "make programs sudo make programs-install" 
I get 

john@john-Lenovo-Yoga-2-Pro:~/yoga-laptop$ make programs sudo make programs-install
cd sensors && make all
make[1]: Entering directory `/home/john/yoga-laptop/sensors'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/john/yoga-laptop/sensors'
make: *** No rule to make target `sudo'.  Stop.

Am I missing anything? Or did it run already?

**Comment by pfps** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

You need to run two commands:

make programs

which compiles and links, and

sudo make install

which does the install part as root.

peter


On 05/29/2015 07:59 AM, Johnathan Nader wrote:
> So I went through the readme and installed all the missing depencies. I
> have kernel 3.16.0-38. I'm not sure if I am doing it correctly though, I
> pulled the git. Extracted the tar.
> 
> Not sure if it ran already or not, but when I run "make programs sudo
> make programs-install" I get
> 
> john@john-Lenovo-Yoga-2-Pro:~/yoga-laptop$ make programs sudo make 
> programs-install cd sensors && make all make[1]: Entering directory
> |/home/john/yoga-laptop/sensors' make[1]: Nothing to be done for|all'. 
> make[1]: Leaving directory |/home/john/yoga-laptop/sensors' make: *** No
> rule to make target|sudo'. Stop.
> 
> Am I missing anything? Or did it run already?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/pfps/yoga-laptop/issues/40>.
> 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJVacpqAAoJECjN6+QThfjziUEH/2G8SpajoVlF+wePDwLT6GBV
+JGXw2R1836/G0+mLgYT8t5AFQLuojwGsbcKR/p63Jx0o7XfKdpSJnk9lHTgfDgn
6918tGvkmw3cA9rg1qBurtETWz2bdSHgzJnUKJ1zuBxm2AictWG7a8DME85mqOVv
unoPwRgma8PT+1pzEfePkAjRh2+Ynv8niCCzg3ld8bdLTORFuXLhDlZfarnxnQHF
vMdTGY4dgdh2LwF9J4wSVh4BbYRAP2Ydc6Op0e+5hPZ1vbYDZy0PPjXvpV541LOE
51XDBsIebcuOWOC7lt9dQC7wUugNVI6+qJa8tLsXIrOIqYyJO7M3mpn64CMkZbQ=
=EsZk
-----END PGP SIGNATURE-----

**Comment by interneteur** [comment]
When I run those commands I get the same output

john@john-Lenovo-Yoga-2-Pro:~/yoga-laptop$ make programs
cd sensors && make all
make[1]: Entering directory `/home/john/yoga-laptop/sensors'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/john/yoga-laptop/sensors'
john@john-Lenovo-Yoga-2-Pro:~/yoga-laptop$ sudo make install
[sudo] password for john: 
make: *** No rule to make target `install'.  Stop.
john@john-Lenovo-Yoga-2-Pro:~/yoga-laptop$

**Comment by pfps** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Oops, it's

  sudo make programs-install

peter


On 05/30/2015 10:44 AM, Johnathan Nader wrote:
> When I run those commands I get the same output
> 
> john@john-Lenovo-Yoga-2-Pro:~/yoga-laptop$ make programs cd sensors &&
> make all make[1]: Entering directory |/home/john/yoga-laptop/sensors' 
> make[1]: Nothing to be done for|all'. make[1]: Leaving directory
> |/home/john/yoga-laptop/sensors' 
> john@john-Lenovo-Yoga-2-Pro:~/yoga-laptop$ sudo make install [sudo]
> password for john: make: *** No rule to make target|install'. Stop. 
> john@john-Lenovo-Yoga-2-Pro:~/yoga-laptop$
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/pfps/yoga-laptop/issues/40#issuecomment-107070470>.
> 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJVafoHAAoJECjN6+QThfjz7rMH/R6yHMs/FgFtI0g64GRG0tgC
WG1eJJpIjYNYsIPRp7O7+p0Q3Y05FOcQ6Ph3T88Dao9YgCfXRXC3rGo1HZ1XkM7U
uvhju54vsQJ0s3zUJX1eLQ5nd3uNf8/8o+t9L5zQAnHYG/MkqQ7O1FmjDG+g8vIG
+EsvXGnZ7mbabT30eRRGobm9lHsaW1mv60gVAFzp4LbHRpQDzwBjgT4rfww0JqfO
x68V0RbEOU4F+2MkLd9WbslY/BDTzwVlBKN8bCL3nhYJ04UbbPimwvI5dhG0zu65
ZCsUdw80FA8i1UK79ZSKNpLtw2RHktOhmJPWw8KM0bkAVuXrj3nI4+6i+NeHV0g=
=AvKF
-----END PGP SIGNATURE-----

**Comment by interneteur** [comment]
I ran 
```
sudo make programs-install
```

And got 
```
cd sensors && make install
make[1]: Entering directory `/home/john/yoga-laptop/sensors'
Making the control files writable by you
chgrp john /sys/bus/iio/devices/iio:device*/scan_elements/in_*_en /sys/bus/iio/devices/iio:device*/buffer/* /sys/bus/iio/devices/iio:device*/trigger/current_trigger
chmod g+w /sys/bus/iio/devices/iio:device*/scan_elements/in_*_en /sys/bus/iio/devices/iio:device*/buffer/* /sys/bus/iio/devices/iio:device*/trigger/current_trigger
chgrp john /dev/iio:device*
chmod g+rw /dev/iio:device*
install --owner=root --group=root --mode=755 orientation /usr/bin
install --owner=root --group=root --mode=755 light /usr/bin
NOTE: In most cases you also need to install drivers from the drivers directory
make[1]: Leaving directory `/home/john/yoga-laptop/sensors'
```

But the rotation still doesn't work and the touchpad is still active and able to scroll when I have it tablet mode

**Comment by pfps** [comment]
You also have to run the actual program.
  orientation
That should start rotation, and also produce output like
  idefix yoga-laptop> orientation 
iio device number being used is 5
iio trigger number being used is 5
Orientation 1, x:   -8, y: -732, z: -698
Orientation at 0.0 is normal
Orientation 1, x:   -7, y: -732, z: -714
Orientation at 1.0 is normal
ROTATE to normal
Orientation 2, x: -905, y: -263, z: -204
Orientation at 2.0 is right
Orientation 2, x: -968, y: -188, z: -163
Orientation at 3.0 is right
ROTATE to right
Orientation 1, x: -416, y: -705, z: -301
Orientation at 4.0 is normal
Orientation 1, x:  -23, y: -727, z: -722
Orientation at 5.0 is normal
ROTATE to normal

**Comment by interneteur** [comment]
Thank you so much!!
