### ISSUE TITLE
Ubuntu 15.10 - notify.h not found

### ISSUE THREAD

**Issue by tomheinisch** [pfps/yoga-laptop#51]
make
    cd sensors && make all
    make[1]: Entering directory '/home/tom/yoga-laptop/sensors'
    cc orientation.c  -o orientation
    ^[[Aorientation.c:32:30: fatal error: libnotify/notify.h: No such file or directory 
    compilation terminated.
    Makefile:16: recipe for target 'orientation' failed
    make[1]: *** [orientation] Error 1

Any ideas?

Many thanks,
Tom

**Comment by chhtz** [comment]
You need to install libnotify-dev

**Comment by tomheinisch** [comment]
Thanks for that - it seems to have brought me one step further, but now another error message 

    make programs
    cd sensors && make all
    make[1]: Entering directory '/home/tom/yoga-laptop/sensors'
    cc orientation.c  -o orientation
    In file included from orientation.c:32:0:
    /usr/include/libnotify/notify.h:25:18: fatal error: glib.h: No such file or directory
    compilation terminated.
    Makefile:16: recipe for target 'orientation' failed
    make[1]: *** [orientation] Error 1
    make[1]: Leaving directory '/home/tom/yoga-laptop/sensors'
    Makefile:9: recipe for target 'programs' failed
    make: *** [programs] Error 2

After that, I tried to find out whether libglib-2.0 was properly installed - it seems it was, under /usr/include/glib-2.0.

/usr/include/libnotify/notify.h tries to include it using
    #include <glib.h>
That would refer to /usr/include/glib.h - does that cause the problem?

Thanks again.

**Comment by chhtz** [comment]
What does ``pkg-config --cflags --libs libnotify`` return?

**Comment by tomheinisch** [comment]
-pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64 linux-gnu/glib-2.0/include -lnotify -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0

**Comment by chhtz** [comment]
It seems, in my pull-request #47, I accidentally added line 17 instead of replacing line 16.
@pfps Can you remove that line from the Makefile (I don't want to open a PR for that single line)?

**Comment by pfps** [comment]
What is the exact change required?

**Comment by chhtz** [comment]
Remove this line:
https://github.com/pfps/yoga-laptop/blob/master/sensors/Makefile#L16

**Comment by pfps** [comment]
Should be done

**Comment by tomheinisch** [comment]
This is now solved.
