### ISSUE TITLE
Progress on other sensors

### ISSUE THREAD

**Issue by Buri** [pfps/yoga-laptop#7]
Hey,
how's progress on other sensors going? Any updates?

I have just upgraded to latest stable kernel (3.14.2), but there is still no official support for the remaining four sensors.

**Comment by alexandre-mbm** [comment]
> I have just updated to kernel 3.17.2 and I am now detecting 6 iio sensors - accel_3d, magn_3d, dev_rotation, als, gyro_3d, incli_3d. I am gonna test them during the week.

@Buri, excuse me my question do not be about the yoga-laptop. I want improve the [InspironAutoRotateService] to use with the hinge. I need read about iio sensors. Do you can help me by indicating references? I need understand them more and mere debug is much hard for me.

[InspironAutoRotateService]: jimmy00784/InspironAutoRotateService
